---
on:
  workflow_call:
    inputs:
      semrel_config_version:
        default: "1.x"
        type: string
        required: false
name: semantic release
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install nodejs
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install
          @gliech/semantic-release-config-github-generic@${{ inputs.semrel_config_version }}

      - name: Create new release
        run: npx semantic-release --extends
          @gliech/semantic-release-config-github-generic
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
